### ISSUE TITLE
Request for inclusion of basicVSR++ model

### ISSUE THREAD

**Issue by meadewaking** [mafiosnik777/enhancr#11]
Hi,

I hope this issue finds you well. I am a user of this repository and I have noticed that the basicVSR++ model is currently not included.

I would like to request that the basicVSR++ model be added to the repository. It has excellent video super-resolution performance.

Thank you for your time and consideration.

Best regards

**Comment by mafiosnik777** [comment]
![image](https://user-images.githubusercontent.com/108760201/217243100-93a30a38-76df-427e-b03e-d7a42fab14be.png)
[🤨](https://emojipedia.org/face-with-raised-eyebrow/)

I wouldn't really call this "excellent video super-resolution performance". 
So no, not worth it.
