### ISSUE TITLE
enhancr does not like certain MKV files

### ISSUE THREAD

**Issue by KakarottoCake** [mafiosnik777/enhancr#13]
I tried using a 480p anime (Dragon Ball Z). And I believe that since it has chapters, Enhancr does not like it. please fix

**Comment by couleurm** [comment]
could you send screenshots of the errors you encounter, and possibly upload a copy of that mkv file so mafio can test it on his computer?

**Comment by mafiosnik777** [comment]
@KakarottoCake 
Chapters shouldn't affect it at all. Please send %appdata%/.enhancr/log.txt. I can't do anything without logs.

**Comment by mafiosnik777** [comment]
Should be fixed with https://github.com/mafiosnik777/enhancr/commit/d5760c38685391eac017086dba3420618bd9942a.
Disable Preview for now until next update releases.
