### ISSUE TITLE
Need internet connection to use app?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [mafiosnik777/enhancr#14]
If I join the patreon to use the app, does it need to be connected to the internet every time I use it?  If I cancel the patreon subscription can I still use the last version of the app that I have installed?  Or am I paying $120 a year to use the app?

**Comment by mafiosnik777** [comment]
@noobtoob4lyfe
No, once a month to authenticate the current billing period. After that you can use it offline or whatever for that current month. Soon there'll be a free version with some cut-down features as well.

**Comment by noobtoob4lyfe** [comment]
Thanks for your reply.  So if I became a patreon member for lets say 1 year only, after that year is up I would not be able to use the app that I have installed anymore unless I join for another year?  Do I have that right?
