### ISSUE TITLE
No Uninstaller:)

### ISSUE THREAD

**Issue by humzasadiq** [mafiosnik777/enhancr#15]
My gpu isnt support and its not uninstalling;(

**Comment by mafiosnik777** [comment]
Yes Uninstaller:)

![](https://i.imgur.com/adD7HEg.png)


![](https://i.imgur.com/QCPjbC4.png)

What GPU do you have? @humzasadiq

**Comment by humzasadiq** [comment]
I installed the latest version from your repo. I was uninstalling the same way you mentioned but it kept opening the installer. In the UninstalString in the registry it was directing towards the installer and no uninstaller was present in the directory.  At last i force uninstalled it from the registry and deleted all files. I have a Nvidia Quadro K2000. I think it doesn't have support for Vulkan ig. When i click on enhance it just keeps loading on zero %. and negligible resources being used. Sometimes it just goes from 0 to 100 in a second and says successfully completed in terminal but no video is saved in the output directory.
Nevertheless, the UI was great:))

**Comment by mafiosnik777** [comment]
K2000 is 10 years old at this point now, but if i recall correctly Kepler was the first architecture to support Vulkan, so should theoretically still work. 

That's just UI bugs, I fucked up somewhere majorly for some people, will fix soon. @humzasadiq

**Comment by TukangM** [comment]
![image](https://github.com/mafiosnik777/enhancr/assets/91467886/d0031ad3-d4ec-4e37-8577-9847ad459b2e)
cannot uninstall
