### ISSUE TITLE
Error with video

### ISSUE THREAD

**Issue by KK-Designs** [mafiosnik777/enhancr#22]
Im getting the following error show below when trying to upscale a video:
```
[enhancr] Preparing media for upscaling process..

[enhancr] Encoding parameters: -c:v libx264 -crf 16 -preset slow -x264-params direct=spatial:me=umh -pix_fmt yuv420p

[enhancr] Scale: 2x

[enhancr] Mode: Upscaling - RealESRGAN (DirectML)

[enhancr] Starting upscaling process..


[Pipe] Starting video output | Threads: 8 | Streams: 2

[Pipe] Script evaluation done in 2.02 seconds
[Pipe] 2023-06-13 18:49:43.3519796 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned

[Pipe] while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\onnxruntime\onnxruntime\onnxruntime\core\providers\dml\DmlExecutionProvider\src\FusedGraphKernel.cpp(365)\onnxruntime.dll!00007FFA8BA1E00A: (caller: 00007FFA8BA1C7FC) Exception(2) tid(5780) 8007000E Not enough memory resources are available to complete this operation.
[Pipe] Error: Failed to retrieve frame 1 with error: operator (): 'ortapi-&gt;RunWithBinding(resource.session, nullptr, resource.binding)' failed: Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\onnxruntime\onnxruntime\onnxruntime\core\providers\dml\DmlExecutionProvider\src\FusedGraphKernel.cpp(365)\onnxruntime.dll!00007FFA8BA1E00A: (caller: 00007FFA8BA1C7FC) Exception(2) tid(5780) 8007000E Not enough memory resources are available to complete this operation.

[Pipe] Output 8 frames in 16.06 seconds (0.50 fps)
[Pipe] 

[enhancr] Finishing up upscaling..

[enhancr] Muxing in streams..

[Pipe] [matroska,webm @ 00000264e9d5af40] Duplicate element

[matroska,webm @ 00000264e9d5af40] 0x00 at pos 110 (0x6e) invalid as first byte of an EBML number

[matroska,webm @ 00000264e9d5af40] Duplicate element

[matroska,webm @ 00000264e9d5af40] 0x00 at pos 202 (0xca) invalid as first byte of an EBML number

[matroska,webm @ 00000264e9d5af40] Element at 0x67 ending at 0x7cec0100000070 exceeds containing master element ending at 0x1413

C:\Users\KKart\AppData\Local\Temp\enhancr\1686707366850.mkv: End of file

[enhancr] Completed upscaling

[enhancr] Completed queue with 0 error(s). // Not true
```
This happens to a specific video and I've tried reencoding it still doesn't work.

**Comment by styler00dollar** [comment]
It clearly says `Not enough memory resources are available to complete this operation`.

**Comment by mafiosnik777** [comment]
☝️

As @styler00dollar said, you're running out of memory. Try setting concurrent streams to 1.
If that results in the same error use tiling.
@KK-Designs

**Comment by mafiosnik777** [comment]
Yeah, the smaller tiles you use, the slower it gets. Also uses less VRAM though the lower you go. Like I said try 1 stream first, if that doesn't work try smaller tiles until it works. @KK-Designs

**Comment by KK-Designs** [comment]
Setting it to 1 stream made it work but it made it go extremely slow (0.01 FPS) and it seems to be an issue with the VRAM
![image](https://github.com/mafiosnik777/enhancr/assets/71038229/0f5124b9-fd65-4692-8774-8551dd51df3d)

Tiling barely uses any VRAM (0.5 GB) and goes faster at 0.6 FPS. Which may seem slow but the video I am upscaling is already in 4K and I wanted to see if I can get it to 8K. Its slow so I guess I should probably start from 1080p and then use 4x.

**Comment by mafiosnik777** [comment]
These speeds are to be expected at 4k, lol.

**Comment by KK-Designs** [comment]
Yeah, but when using the app normally I get 7FPS. Also, I wanted to say this app so far gives the best quality out of all the ones I've used so far. The UI is very nice and easy to use. There is one more bug that I wanted to report and that is the `[Pipe] Error: fwrite() call failed when writing frame: 144, plane: 0, errno: 22` that happens sometimes.

**Comment by mafiosnik777** [comment]
I already told you, speeds depend on resolution. 4k is not viable to upscale. 

That's not a bug on its own, it always happens in conlusion of something else, like running out of VRAM.
