### ISSUE TITLE
Which engine gives the best quality? [QUESTION]

### ISSUE THREAD

**Issue by KK-Designs** [mafiosnik777/enhancr#23]
Which engine gives the best quality? NCNN, DirectML, or TensorRT on Windows? I would also like to know which one is the fastest. Would be nice to have this information as a hover tooltip.

**Comment by Bubblemint864** [comment]
There is no quality difference between frameworks. TensorRT is the fastest as it tunes models to your specific GPU - but requires an Nvidia GPU. [See the benchmarks here](https://github.com/mafiosnik777/enhancr#benchmarks).
