### ISSUE TITLE
can't get normal esrgan to work

### ISSUE THREAD

**Issue by hugoCC1** [mafiosnik777/enhancr#4]
got this error:
clip = core.trt.Model(clip, engine_path=engine, num_streams=streams) File "src\cython\vapoursynth.pyx", line 2565, in vapoursynth.Function.__call__vapoursynth.Error: operator (): no valid optimization profile found

i used a model called 2X_DigitalFilmV5_Lite.pth
btw the realesrgan models worked just fine just the esrgan one that i had this problem with
here is the log
[log.txt](https://github.com/mafiosnik777/enhancr/files/10100772/log.txt)

**Comment by mafiosnik777** [comment]
> got this error: clip = core.trt.Model(clip, engine_path=engine, num_streams=streams) File "src\cython\vapoursynth.pyx", line 2565, in vapoursynth.Function.__call__vapoursynth.Error: operator (): no valid optimization profile found
> 
> i used a model called 2X_DigitalFilmV5_Lite.pth btw the realesrgan models worked just fine just the esrgan one that i had this problem with here is the log [log.txt](https://github.com/mafiosnik777/enhancr/files/10100772/log.txt)

No optimization profile found, means that shapes are not fitting.

"--minShapes=input:1x3x8x8 --optShapes=input:1x3x360x270 --maxShapes=input:1x3x720x540"

What res is your input and are u using tiling?

**Comment by hugoCC1** [comment]
input res is 640x480 and no tiling

**Comment by hugoCC1** [comment]
thanks i mange to get it working by making shape res 1280x720 
thanks for your time and hardwork :)
