### ISSUE TITLE
Implement NVIDIA OFA FRUC as an option for video frame interpolation

### ISSUE THREAD

**Issue by brokeDude2901** [mafiosnik777/enhancr#9]
https://docs.nvidia.com/video-technologies/optical-flow-sdk/nvfruc-programming-guide/index.html

Example built win64 binary: https://github.com/brokeDude2901/NvOFFRUCSample

Pros:
- Low VRAM usage, only use Tensor Cores

Cons:
- Require at least a NVIDIA GPU Turing

**Comment by mafiosnik777** [comment]
I'm sorry, but we have better Optical Flow solutions already in enhancr. The results aren't looking very good either, so not really worth to implement.
